[package]
name = "bmt"
version = "0.1.0"
authors = ["sdclibbery <sdclibbery@googlemail.com>"]
edition = "2018"

[dependencies]
termion = "*"
bitmex = "0.1.5"
futures = "0.1.27"
tokio = "0.1.21"
simplelog = "0.5.3"
